"""Add encryption preference

Revision ID: 2588dcdac0ee
Revises: 075c04a5f2db
Create Date: 2026-06-29 13:55:21.068584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2588dcdac0ee'
down_revision = '075c04a5f2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_enabled', sa.Boolean(), nullable=False, server_default=sa.text('1')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('encryption_enabled')

    # ### end Alembic commands ###
